services:
  backend:
    container_name: spin
    build: .
    env_file: .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_DBNAME
      - SALT_ROUNDS
      - JWT_KEY
      - CERBROS_URL
      - AZURE_CLIENTID
      - AZURE_CLIENTSECRET
      - AZURE_TENANTID
      - AZURE_USERNAME
      - AZURE_PASSWORD
      - AZURE_ONELAKEURL
      - PORT
      - BACKEND_URL
    depends_on:
      - db
      - cerbos
    networks:
      - db
    ports:
      - "3000:3000"
  migration:
    image: migrate/migrate
    networks:
      - db
    volumes:
      - ./migrations:/migrations
    env_file: .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DBNAME
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DBNAME?sslmode=disable",
        "up",
      ]
    links:
      - db
  db:
    container_name: postgres
    image: postgres
    env_file: .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGDATA
      - POSTGRES_DB
    volumes:
      - db:/data/postgres
    networks:
      - db
  cerbos:
    container_name: cerbros
    image: ghcr.io/cerbos/cerbos:0.40.0
    ports:
      - "3592:3592"
    volumes:
      - ./policies:/policies
    networks:
      - db
  py_be:
    container_name: py_be
    image: suryaaprakassh/ms_py_spin
    ports:
      - "5000:5000"
    networks:
      - db
    environment:
      - AZURE_ENDPOINT
      - AZURE_OPENAI_API_KEY
      - AZURE_OPENAI_API_VERSION
      - AZURE_DEPLOYMENT
      - VECTOR_STORE_ADDRESS
      - VECTOR_STORE_PASSWORD
      - LLAMA_ENDPOINT
      - LLAMA_API_KEY
      - LLAMA_DEPLOYMENT
      - LANGCHAIN_API_KEY
      - LANGCHAIN_TRACING_V2
      - LANGCHAIN_ENDPOINT
      - LANGCHAIN_PROJECT
networks:
  db:
    driver: bridge
volumes:
  db:
